# name: CI/CD
#
# on:
#   push:
#     branches: [ "main" ]
#
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#
#       - name: Set up JDK
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '17'
#
#       - name: Build with Gradle
#         run: ./gradlew clean build -x test
#
#       - name: Login to Docker Hub
#         run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#
#       - name: Build & Push Docker image
#         run: |
#           IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/be-app
#           TAG=${{ github.sha }}
#           docker build -t $IMAGE:$TAG -t $IMAGE:latest .
#           docker push $IMAGE:$TAG
#           docker push $IMAGE:latest
#
#       - name: Set up kubectl
#         uses: azure/setup-kubectl@v3
#
#       - name: Deploy to Kubernetes
#         run: |
#           echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig.yaml
#           export KUBECONFIG=kubeconfig.yaml
#           IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/be-app
#           TAG=${{ github.sha }}
#           kubectl -n cicd set image deploy/be-app be-app=$IMAGE:$TAG
#           kubectl -n cicd rollout status deploy/be-app --timeout=120s
