name: CI/CD with ArgoCD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle build
      - name: Build Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # Docker login
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Image build & push
      - name: Build & Push Docker Image
        id: tag
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/sanjifarm-be
        run: |
          TAG=git-${GITHUB_SHA}
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT

  gitops:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitLab manifest repo
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_MANIFEST_REPO }} manifest
          cd manifest
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update image tag
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/sanjifarm-be
          IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}
        run: |
          cd manifest/k8s
          sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|" deployment.yaml

      - name: Commit & Push
        run: |
          cd manifest
          git add .
          git commit -m "Update image tag to ${{ needs.build.outputs.IMAGE_TAG }}" || echo "No changes to commit"
          git push
